In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("nba_games.csv", index_col=0)

In [3]:
df = df.sort_values("date")

In [4]:
df = df.reset_index(drop=True)

In [5]:
del df["mp.1"]
del df["mp_opp.1"]
del df["index_opp"]

In [6]:
df = df.copy()
def add_target(team):
    team["target"] = team["won"].shift(-1)
    return team
df["target"] = df.groupby("team")["won"].shift(-1)

In [7]:
df["team"]

0        BOS
1        CLE
2        HOU
3        GSW
4        WAS
        ...
20249    CHO
20250    ATL
20251    ORL
20252    MEM
20253    SAS
Name: team, Length: 20254, dtype: object

In [8]:
df[df["team"]=="WAS"]

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,seasons,date,won,target
4,240.0,42.0,97.0,0.433,6.0,22.0,0.273,30.0,38.0,0.789,...,31.2,148.0,125.0,PHI,115,0,2018,2017-10-18,True,True
33,240.0,40.0,75.0,0.533,6.0,17.0,0.353,29.0,35.0,0.829,...,43.6,215.0,122.0,DET,111,0,2018,2017-10-20,True,True
91,240.0,37.0,84.0,0.440,9.0,30.0,0.300,26.0,28.0,0.929,...,35.1,272.0,115.0,DEN,104,1,2018,2017-10-23,True,False
108,265.0,39.0,95.0,0.411,6.0,26.0,0.231,15.0,23.0,0.652,...,32.9,129.0,98.0,LAL,102,1,2018,2017-10-25,False,False
147,240.0,43.0,97.0,0.443,15.0,33.0,0.455,16.0,22.0,0.727,...,30.9,210.0,122.0,GSW,120,1,2018,2017-10-27,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20136,240.0,35.0,86.0,0.407,12.0,45.0,0.267,8.0,10.0,0.800,...,26.9,208.0,112.0,BOS,124,1,2025,2025-04-06,False,False
20161,240.0,38.0,91.0,0.418,11.0,39.0,0.282,11.0,15.0,0.733,...,26.6,145.0,112.0,IND,104,1,2025,2025-04-08,False,False
20165,240.0,34.0,87.0,0.391,10.0,33.0,0.303,25.0,30.0,0.833,...,31.5,165.0,109.0,PHI,122,0,2025,2025-04-09,False,False
20213,240.0,35.0,91.0,0.385,10.0,41.0,0.244,9.0,12.0,0.750,...,31.2,261.0,97.0,CHI,119,1,2025,2025-04-11,False,True
20237,240.0,46.0,90.0,0.511,16.0,37.0,0.432,11.0,17.0,0.647,...,33.1,162.0,125.0,MIA,118,1,2025,2025-04-13,True,NaN

In [9]:
df["target"][pd.isnull(df["target"])] = 2

C:\Users\tahsi\AppData\Local\Temp\ipykernel_22212\1618397414.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["target"][pd.isnull(df["target"])] = 2

In [10]:
df["target"] = df["target"].astype(int, errors="ignore")

In [11]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,seasons,date,won,target
0,240.0,36.0,88.0,0.409,8.0,32.0,0.250,19.0,25.0,0.760,...,27.3,138.0,107.0,CLE,102,1,2018,2017-10-17,False,0
1,240.0,38.0,83.0,0.458,5.0,22.0,0.227,21.0,25.0,0.840,...,29.9,129.0,112.0,BOS,99,0,2018,2017-10-17,True,1
2,240.0,47.0,97.0,0.485,15.0,41.0,0.366,13.0,19.0,0.684,...,32.6,250.0,127.0,GSW,121,1,2018,2017-10-17,True,1
3,240.0,43.0,80.0,0.538,16.0,30.0,0.533,19.0,21.0,0.905,...,31.2,152.0,126.0,HOU,122,0,2018,2017-10-17,False,1
4,240.0,42.0,97.0,0.433,6.0,22.0,0.273,30.0,38.0,0.789,...,31.2,148.0,125.0,PHI,115,0,2018,2017-10-18,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20249,240.0,32.0,85.0,0.376,11.0,39.0,0.282,11.0,18.0,0.611,...,34.3,157.0,107.0,BOS,93,1,2025,2025-04-13,False,2
20250,240.0,47.0,88.0,0.534,17.0,40.0,0.425,6.0,10.0,0.600,...,33.6,191.0,129.0,ORL,105,0,2025,2025-04-13,True,2
20251,240.0,40.0,88.0,0.455,15.0,35.0,0.429,10.0,15.0,0.667,...,32.5,160.0,117.0,ATL,117,1,2025,2025-04-13,False,2
20252,240.0,52.0,104.0,0.500,15.0,41.0,0.366,13.0,15.0,0.867,...,31.7,143.0,137.0,DAL,97,0,2025,2025-04-13,True,2
20253,240.0,43.0,84.0,0.512,11.0,32.0,0.344,28.0,32.0,0.875,...,32.3,230.0,131.0,TOR,118,0,2025,2025-04-13,True,2

In [12]:
df["won"].value_counts()

won
False    10127
True     10127
Name: count, dtype: int64

In [13]:
df["target"].value_counts()

target
0    10112
1    10112
2       30
Name: count, dtype: int64

In [14]:
nulls = pd.isnull(df)

In [15]:
nulls = nulls.sum()

In [16]:
nulls = nulls[nulls>0]

In [17]:
nulls

ft%                 1
gmsc            20254
+/-             20254
mp_max          20254
mp_max.1        20254
ft%_max             1
+/-_max            15
ft%_opp             1
gmsc_opp        20254
+/-_opp         20254
mp_max_opp      20254
mp_max_opp.1    20254
ft%_max_opp         1
+/-_max_opp        15
dtype: int64

In [18]:
big_nulls = nulls[nulls==19530]

In [19]:
big_nulls

Series([], dtype: int64)

In [20]:
nulls

ft%                 1
gmsc            20254
+/-             20254
mp_max          20254
mp_max.1        20254
ft%_max             1
+/-_max            15
ft%_opp             1
gmsc_opp        20254
+/-_opp         20254
mp_max_opp      20254
mp_max_opp.1    20254
ft%_max_opp         1
+/-_max_opp        15
dtype: int64

In [21]:
valid_columns = df.columns[~df.columns.isin(big_nulls.index)]

In [22]:
valid_columns

Index(['mp', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'ft%',
       ...
       'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp',
       'home_opp', 'seasons', 'date', 'won', 'target'],
      dtype='object', length=152)

In [23]:
df = df[valid_columns].copy()

In [24]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,seasons,date,won,target
0,240.0,36.0,88.0,0.409,8.0,32.0,0.250,19.0,25.0,0.760,...,27.3,138.0,107.0,CLE,102,1,2018,2017-10-17,False,0
1,240.0,38.0,83.0,0.458,5.0,22.0,0.227,21.0,25.0,0.840,...,29.9,129.0,112.0,BOS,99,0,2018,2017-10-17,True,1
2,240.0,47.0,97.0,0.485,15.0,41.0,0.366,13.0,19.0,0.684,...,32.6,250.0,127.0,GSW,121,1,2018,2017-10-17,True,1
3,240.0,43.0,80.0,0.538,16.0,30.0,0.533,19.0,21.0,0.905,...,31.2,152.0,126.0,HOU,122,0,2018,2017-10-17,False,1
4,240.0,42.0,97.0,0.433,6.0,22.0,0.273,30.0,38.0,0.789,...,31.2,148.0,125.0,PHI,115,0,2018,2017-10-18,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20249,240.0,32.0,85.0,0.376,11.0,39.0,0.282,11.0,18.0,0.611,...,34.3,157.0,107.0,BOS,93,1,2025,2025-04-13,False,2
20250,240.0,47.0,88.0,0.534,17.0,40.0,0.425,6.0,10.0,0.600,...,33.6,191.0,129.0,ORL,105,0,2025,2025-04-13,True,2
20251,240.0,40.0,88.0,0.455,15.0,35.0,0.429,10.0,15.0,0.667,...,32.5,160.0,117.0,ATL,117,1,2025,2025-04-13,False,2
20252,240.0,52.0,104.0,0.500,15.0,41.0,0.366,13.0,15.0,0.867,...,31.7,143.0,137.0,DAL,97,0,2025,2025-04-13,True,2
20253,240.0,43.0,84.0,0.512,11.0,32.0,0.344,28.0,32.0,0.875,...,32.3,230.0,131.0,TOR,118,0,2025,2025-04-13,True,2

In [25]:
nulls = pd.isnull(df)

In [26]:
nulls = nulls.sum()

In [27]:
nulls = nulls[nulls>0]

In [28]:
nulls

ft%                 1
gmsc            20254
+/-             20254
mp_max          20254
mp_max.1        20254
ft%_max             1
+/-_max            15
ft%_opp             1
gmsc_opp        20254
+/-_opp         20254
mp_max_opp      20254
mp_max_opp.1    20254
ft%_max_opp         1
+/-_max_opp        15
dtype: int64

In [29]:
cols_to_check = nulls.index.tolist()
df = df.dropna(subset=cols_to_check)

In [30]:
nulls = pd.isnull(df)
nulls = nulls.sum()
nulls = nulls[nulls>0]
nulls

Series([], dtype: int64)

In [31]:
df

Empty DataFrame
Columns: [mp, fg, fga, fg%, 3p, 3pa, 3p%, ft, fta, ft%, orb, drb, trb, ast, stl, blk, tov, pf, pts, gmsc, +/-, ts%, efg%, 3par, ftr, orb%, drb%, trb%, ast%, stl%, blk%, tov%, usg%, ortg, drtg, mp_max, mp_max.1, fg_max, fga_max, fg%_max, 3p_max, 3pa_max, 3p%_max, ft_max, fta_max, ft%_max, orb_max, drb_max, trb_max, ast_max, stl_max, blk_max, tov_max, pf_max, pts_max, gmsc_max, +/-_max, ts%_max, efg%_max, 3par_max, ftr_max, orb%_max, drb%_max, trb%_max, ast%_max, stl%_max, blk%_max, tov%_max, usg%_max, ortg_max, drtg_max, team, total, home, mp_opp, fg_opp, fga_opp, fg%_opp, 3p_opp, 3pa_opp, 3p%_opp, ft_opp, fta_opp, ft%_opp, orb_opp, drb_opp, trb_opp, ast_opp, stl_opp, blk_opp, tov_opp, pf_opp, pts_opp, gmsc_opp, +/-_opp, ts%_opp, efg%_opp, 3par_opp, ftr_opp, orb%_opp, ...]
Index: []

[0 rows x 152 columns]

In [32]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\tahsi\downloads\anaconda3\lib\site-packages (1.3.1)
Requirement already satisfied: numpy<2.0,>=1.17.3 in c:\users\tahsi\downloads\anaconda3\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.5.0 in c:\users\tahsi\downloads\anaconda3\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\tahsi\downloads\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\tahsi\downloads\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)
Note: you may need to restart the kernel to use updated packages.

In [33]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier

rr=RidgeClassifier(alpha=1)

split = TimeSeriesSplit(n_splits=3)
sfs = SequentialFeatureSelector(rr, n_features_to_select=30, direction = "forward", cv=split)

In [34]:
#columns we aren't going to scale
removed_columns = ["seasons", "date", "won", "target", "team", "team_opp"]

In [35]:
#columns we do scale
selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [36]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df[selected_columns]=scaler.fit_transform(df[selected_columns])

ValueError: Found array with 0 sample(s) (shape=(0, 146)) while a minimum of 1 is required by MinMaxScaler.

In [ ]:
df

In [ ]:
sfs.fit(df[selected_columns], df["target"])

In [ ]:
predictors = list(selected_columns[sfs.get_support()])

In [ ]:
predictors

In [ ]:
df.rename(columns={"seasons": "season"}, inplace=True)

In [ ]:
def backtest(data, model, predictors, start=2, step=1):
    all_predictions = []
    seasons = sorted(data["season"].unique())
    for i in range(start, len(seasons),step):
        season = seasons[i]
        train = data[data["season"] < season]
        test=data[data["season"] == season]
        model.fit(train[predictors], train["target"])
        preds = model.predict(test[predictors])#default numpyarray return
        preds = pd.Series(preds, index=test.index)
        combined = pd.concat([test["target"], preds], axis=1)
        combined.columns = ["actual", "prediction"]
        all_predictions.append(combined)
    return pd.concat(all_predictions)

In [ ]:
sorted(df["season"].unique())

In [ ]:
predictions = backtest(df, rr, predictors)

In [ ]:
predictions

In [ ]:
from sklearn.metrics import accuracy_score
predictions = predictions[predictions["actual"] != 2]
accuracy_score(predictions["actual"], predictions["prediction"])

In [ ]:
df.groupby("home").apply(lambda x: x[x["won"] == 1].shape[0] / x.shape[0])

In [ ]:
df_rolling = df[list(selected_columns) + ["won", "team", "season"]]

In [ ]:
df_rolling

In [ ]:
def find_team_averages(team):
    numeric_cols = team.select_dtypes(include=["number"])  
    rolling = numeric_cols.rolling(10).mean() 
    return rolling

df_rolling = df.groupby(["team", "season"], group_keys=False).apply(find_team_averages)

In [ ]:
df_rolling

In [ ]:
rolling_cols= [f"{col}_10" for col in df_rolling.columns]
df_rolling.columns = rolling_cols
df = pd.concat([df, df_rolling], axis=1)

In [ ]:
df

In [ ]:
df = df.dropna()

In [ ]:
df

In [ ]:
def shift_col(team, col_name):
    next_col = team[col_name].shift(-1)
    return next_col
def add_col(df, col_name):
    return df.groupby("team", group_keys=False).apply(lambda x:shift_col(x,col_name))
df["home_next"] = add_col(df, "home") #next game
df["team_opp_next"] = add_col(df, "team_opp")
df["date_next"] = add_col(df, "date")

In [ ]:
df

In [ ]:
df = df.copy()

In [ ]:
full = df.merge(
    df[rolling_cols + ["team_opp_next", "date_next", "team"]],
    left_on=["team", "date_next"], 
    right_on=["team_opp_next", "date_next"]
)

In [ ]:
full

In [ ]:
full[["team_x", "team_opp_next_x", "team_y", "team_opp_next_y", "date_next"]]

In [ ]:
removed_columns = list(full.columns[full.dtypes == "object"]) + removed_columns

In [ ]:
#full.columns[full.dtypes == "object"]

In [ ]:
removed_columns

In [ ]:
selected_columns = full.columns[~full.columns.isin(removed_columns)]

In [ ]:
sfs.fit(full[selected_columns], full["target"])

In [ ]:
predictors = list(selected_columns[sfs.get_support()])

In [ ]:
predictors

In [ ]:
predictions = backtest(full, rr, predictors)

In [ ]:
accuracy_score(predictions["actual"],predictions["prediction"])

In [37]:
#how to continue to improve accuracy
#try using more powerful than ridge regression model like random forest classifier
#try out different numbers of features you're selecting for the model (like last 15 games or last 20 games or last 5 games)

In [38]:
#for future get most up to date data 
#fill in home_next, team_opp_next, date_next
#rerun 
#look at any rows with target value 2, find predictions based on that